
[module]
[[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'

theme = 'hugo-theme-relearn'


[params]
#author.name = "sevonj"
description = "TiToMachine User Docs"

themeVariant = 'titodocs'