baseURL = 'https://sevonj.github.io/titouserdoc/'
languageCode = 'en-us'
title = 'TiTo User Docs'

[module]
[[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'

theme = 'hugo-theme-relearn'
[outputs]
    home = [ "HTML", "RSS", "SEARCH"]

[params]
author.name = "sevonj"
description = "TiTo User Docs"
themeVariant = 'titodocs'