
[module]
[[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'

theme = 'hugo-theme-relearn'
[outputs]
    home = [ "HTML", "RSS", "SEARCH"]

[params]
#author.name = "sevonj"
description = "TiToMachine User Docs"

themeVariant = 'titodocs'